language: c

dist:  bionic

addons:
  apt:
    packages:
      - clang
      - nasm
      - libstdc++-5-dev
      - git
      - bash
      - autoconf
      - flex
      - bison
      - sed
    update: true

before_install:
  - echo "before_install"

install:
  - ./travis_build.sh

before_script:
  - echo "before_script"

script:
  - echo "script"
